[package]
name = "agent-parser-ro-test"
version = "0.1.0"
edition = "2021"

[dependencies]
proxy-wasm = "0.2"
agent-parser-ro = "0.1.1"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[profile.release]
lto = true
opt-level = "s"  # Optimize for size (better for WASM)
